name: firefox-lint
on:
  push:
    paths:
      - .github/workflows/lint-firefox.yaml
      - firefox/**
  pull_request:
jobs:
  lint-firefox:
    name: Lint Firefox extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Run web-ext lint
      run: npm exec --yes --package=web-ext@10.7.0 -- web-ext lint --source-dir firefox
